### ISSUE TITLE
OwenQ a != 0

### ISSUE THREAD

**Issue by PharmCat** [Detlew/PowerTOST#3]
Hellow!
Detlew, is it possible to imlement a != 0 for Owen's Q function?

**Comment by Detlew** [comment]
To say it with radio eriwan: In principle yes :-)).

But within the package PowerTOST there is no necessity to do so.
Moreover I haven't seen any occasion with a>0 within the area of power / sample size.
Thus I have no intention to carry the burden to implement something like this.

Could you please elaborate why you ask for an implementation of Owen's Q with a!=0?

**Comment by PharmCat** [comment]
Hi! I am working on JuliaLang package for use in clinical trial and i take your implementation of Owen's Q function (in accordance with GPL (>= 2)) and this function is public now. And i have to make desigion: i can make this function "private" or i have to document that a=0 and remove this function paramether or i have to implemet it.  And if it realy not important and generalized solution not nessesary - i can do nothign with it :).

If it possible i have one more question: 
.power.TOST <- function() , line 29 (power.R) you  can use alfa as vector and then make sum tval[1]+tval[dl] in line 41 (and in other power* funk).  Is it nesessary to support different alpha levels?

**Comment by Detlew** [comment]
Hi PharmCat,
I would make Owen's Q private because it is of not much use taken alone. See the Note in the man page of that function.

But if you decide to implement: Calculate the function from zero upto upper limit and subtract the function calculated from zero upto a as upper limit:
OwensQ(nu, t, delta, a=0, b) - OwensQ(nu, t, delta, a=0, a)
Note that a has to be >0.
Since your question was not a real issue I will close it.

Regarding your additional question I will send you an extra mail.
