### ISSUE TITLE
Query - what equation is used for sampleN.TOST?

### ISSUE THREAD

**Issue by jpkrooney** [Detlew/PowerTOST#7]
Hi. Thanks for this really useful package!

I'm trying to understand the mathematical formula is used in sampleN.TOST(). The helpfile refers to a modified version of Zhang's formula, and the code for .sampleN0_3() is prefaced by the comment "# mixture of old code and Zhang's formula ". However, as the Zhang paper gives a number of formulae, i wasn't sure which one is being used, or how it has been modified.

Could you please specify the final formula used in sampleN.TOST()?
Many thanks!

**Comment by PharmCat** [comment]
There is no analytical solution to get sample size. By default sampleN optimize Owen's Q-Function to get target power.

**Comment by jpkrooney** [comment]
Thanks @PharmCat. So if I understand correctly, the code uses a modified version of Zhang's formula to get a starting n, and then optimises n to reach the target power?

**Comment by Helmut01** [comment]
Exactly. Originally the starting value of the sample size search was based on the large sample approximation. That’s the hidden function `.sampleN0()` - later called in the source’s comment ‘old code’. `.sampleN0_2()` is Zhang’s. It turned out that it results in many iterations if `theta0` is close to one of the limits `theta1`, `theta2`. This was the reason for introducing `.sampleN0_3()`, which is actually used. If you are interested in the background, see e.g., [this article](https://bebac.at/articles/Sample-Size-Estimation-for-Equivalence-Studies-in-a-Parallel-Design.phtml).

**Comment by Detlew** [comment]
Dear friends, thank you for clarifying things to jpkrooney.
Because this was a question for understanding and not a reale issue with the package code I close it without any action.

**Comment by jpkrooney** [comment]
Thank all!

**Comment by PharmCat** [comment]
Maybe make a discussion page?

**Comment by Helmut01** [comment]
What do you mean by that _exactly_?
